# Generated by Django 4.2.20 on 2025-04-22 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0002_book_publisher_alter_book_genre_alter_book_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('BRW', 'borrowed'), ('RTN', 'returned'), ('OVD', 'overdue'), ('LST', 'สูญหาย')], default='BRW', max_length=3, verbose_name='สถานะการยืม')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='วันเวลาที่คืน')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowing_history', to='catalog.book', verbose_name='สิ่งของที่ยืม')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowings', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ยืม')),
            ],
            options={
                'verbose_name': 'รายการยืม',
                'verbose_name_plural': 'รายการยืม',
                'ordering': ['-created_at'],
            },
        ),
    ]
