# Generated by Django 4.2.20 on 2025-04-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
