# Generated by Django 4.2.20 on 2025-05-19 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_book_publisher_alter_book_genre_alter_book_id'),
        ('borrow', '0002_alter_borrow_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowing_history', to='catalog.book', verbose_name='หนังสือที่ยืม'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='status',
            field=models.CharField(choices=[('BRW', 'borrowed'), ('RTN', 'returned'), ('OVD', 'overdue')], default='BRW', max_length=3, verbose_name='สถานะการยืม'),
        ),
    ]
