# Generated by Django 4.2.20 on 2025-04-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genre', models.CharField(choices=[('SCI', 'Science Fiction'), ('DRA', 'Drama'), ('COM', 'Comedy'), ('HOR', 'Horror')], default='SCI', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
